server:
  port: 5022

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/12happy?useUnicode=true&characterEncoding=utf8&allowMultiQueries=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password:

#配置mybatis实体和xml映射
mybatis:
  ##映射xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
